#!/bin/bash
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 50 
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 50 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 51 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 52 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 53 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 54 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 55 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 56 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 57 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 58 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 59 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 60 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 61 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 62 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 63 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 64 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 65 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 66 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 67 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 68 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 69 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 70 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 71 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 72 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 73 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 74 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 75 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 76 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 77 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 78 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 79 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 80 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 81 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 82 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 83 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 84 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 85 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 86 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 87 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 88 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 89 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 90 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 91 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 92 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 93 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 94 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 95 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 96 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 97 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 98 >> output_nospeedup.txt
../../circl/dh/sidh/POC_ATTACK/sike_client 300 400 bit_recovered_nospeedup.txt 99 >> output_nospeedup.txt
